package umari:sqlite@0.1.0;

interface connection {
    use types.{row, sql, sqlite-error, value};

    execute: func(sql: sql, params: list<value>) -> result<s64, sqlite-error>;
    execute-batch: func(sql: sql) -> result<_, sqlite-error>;
    last-insert-rowid: func() -> result<s64, sqlite-error>;
    /// Returns the single matching row. Errors if more than one row is returned.
    query-one: func(sql: sql, params: list<value>) -> result<option<row>, sqlite-error>;
    /// Returns the first matching row or `none`, ignoring any additional rows.
    query-row: func(sql: sql, params: list<value>) -> result<option<row>, sqlite-error>;
}
