package umari:projection@0.1.0;

interface projection-runner {
    use umari:common/types@0.1.0.{dcb-query, deserialize-event-error, stored-event};
    use umari:sqlite/types@0.1.0.{sqlite-error};

    variant error {
        deserialize-event(deserialize-event-error),
        sqlite(sqlite-error),
        other(string),
    }

    resource projection-state {
        constructor() -> result<projection-state, error>;
        query: func() -> dcb-query;
        handler: func(event: stored-event) -> result<_, error>;
    }
}

world projection {
    import umari:sqlite/connection@0.1.0;
    import umari:sqlite/statement@0.1.0;

    export projection-runner;
}
