[book]
title = "The Umari Book"
authors = ["Ari Seyhun"]
language = "en"

[preprocessor.tabs]

[output.html]
mathjax-support = false
smart-punctuation = true
additional-css = ["theme/tabs.css"]
additional-js = ["theme/tabs.js"]
git-repository-url = "https://github.com/tqwewe/umari"
git-repository-icon = "fab-github"
edit-url-template = "https://github.com/tqwewe/umari/edit/main/docs/{path}"

[output.html.fold]
enable = true
level = 1

[rust]
edition = "2024"
